version: '3.9'

services:
  webapp-php80:
    image: lamp-container-from-circleci_webapp-php80
    restart: always
    ports:
      - "3080:80"
      - "4480:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  webapp-php74:
    image: lamp-container-from-circleci_webapp-php74
    restart: always
    ports:
      - "3074:80"
      - "4474:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  webapp-php73:
    image: lamp-container-from-circleci_webapp-php73
    restart: always
    ports:
      - "3073:80"
      - "4473:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  webapp-php72:
    image: lamp-container-from-circleci_webapp-php72
    restart: always
    ports:
      - "3072:80"
      - "4472:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  webapp-php71:
    image: lamp-container-from-circleci_webapp-php71
    restart: always
    ports:
      - "3071:80"
      - "4471:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  webapp-php70:
    image: lamp-container-from-circleci_webapp-php70
    restart: always
    ports:
      - "3070:80"
      - "4470:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certs:/etc/apache2/certs:ro
  db:
    image: circleci/mysql:5.5
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  phpmyadmin:
    image: lamp-container-from-circleci_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - phpmyadmin-session:/sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
#docker volume create --name=example-db
#docker volume create --name=example-phpmyadmin-session
volumes:
  data:
    external:
      name: "example-db"
  phpmyadmin-session:
    external:
      name: "example-phpmyadmin-session"
